### PR TITLE
make mattermost plugin compliant with JCasC

### PR DESCRIPTION
**Pull request by ewelinawilkosz**
Introduced DataBoundSetters and modified configure method to `request.bindJSON` method

changes required to make mattermost plugin configurable via configuration as code plugin (https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md)

no test or changes in pom yet - should be done though, separate PR should happen

### CODE REVIEW

**Comment by ewelinawilkosz** [comment]
cc @ndeloof - have a look please if you have a couple of minutes

**Review by ndeloof — APPROVED** [review]
LGTM

from a purist point of view, `configure` should use a `BulkChange` :
```java
public boolean configure( StaplerRequest req, JSONObject json ) throws FormException {
    try (BulkChange bc = new BulkChange(this)) {
        req.bindJSON(this, json);
        bc.commit();
    }
}
```


and setters should invoke `save()`, so they also can be used from groovy init or other hacky places, as they are declared public.

also see https://github.com/jenkinsci/jenkins/pull/3669

**Comment by jovandeginste** [comment]
@ewelinawilkosz @ndeloof Thanks for this; tested this for a week in our environment, and no issues. New release is pushed!

**Comment by ewelinawilkosz** [comment]
thanks @jovandeginste !

**Pull request merged**
