### PR TITLE
Jenkins Token Expander added

### PR DESCRIPTION
**Pull request by hamzaahmedkhan**
We have added Jenkins Token Expander feature to support Custom messages in Mattermost channel, just like Slack custom messages.

### CODE REVIEW

**Comment by covert8** [comment]
I'll be working on it this weekend. I expect this to be done and merged by monday and the new version to be published on monday itself.

**Comment by hamzaahmedkhan** [comment]
> I'll be working on it this weekend. I expect this to be done and merged by monday and the new version to be published on monday itself.

Sure let me know if anything is not correct from my side.

**Comment by covert8** [comment]
Build 3.1.0 has been released. Thank you for contributing

**Comment by okapia** [comment]
Hi @hamzaahmedkhan and @covert8, my attempts to make use of this were not especially successful but I think I've established that this support is only implemented for Freestyle Projects and not for Pipelines. For the pipeline step, it would appear that a call to the Token macro's expandAll() function is also needed in `MattermostSendStep.java`. That needs a listener and build parameters but I can't work out where the build parameter is supposed to come from in the step. The original patch from this pull request seems to do a certain amount of reformatting and reindentation which doesn't help with reading it.

I'd also suggest that the change from this existing pull request could be somewhat documented by referring to the token macro plugin from the help in `src/main/webapp/help-projectConfig-mattermostCustomAttachmentMessage.html`.

**Pull request merged**
